version: '2'

services:
    webserver:
        image: nginx:latest
        container_name: webserver
        ports:
            - "8080:80"
        volumes:
            - ./:/application
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - application
    backend:
        build: ./docker
        image: mappinggenerator:systems
        container_name: mappingGeneratorSystems
        volumes:
            - ./:/application
            - ./docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - application

networks:
    application:
        driver: bridge
