PREFIX qb:<http://purl.org/linked-data/cube#>
            ASK
            {
                ?observation a qb:Observation .
                ?observation qb:dataSet ?dataset .
                ?observation ?dimension ?dimelement .
                ?observation ?measure ?value .

                ?dataset a qb:DataSet .
                ?dataset qb:structure ?datastructuredefintion .

                ?datastructuredefintion a qb:DataStructureDefinition .
                ?datastructuredefintion qb:component ?dimensionspecification .
                ?datastructuredefintion qb:component ?measurespecification .

                ?dimensionspecification a qb:ComponentSpecification .
                ?dimensionspecification qb:dimension ?dimension .

                ?measurespecification a qb:ComponentSpecification .
                ?measurespecification qb:measure ?measure .
            }
